# fly.toml app configuration file generated for globetrotter-app on 2023-08-25T12:40:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "globetrotter"
primary_region = "bos"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  DJANGO_SETTINGS_MODULE = "Globetrotter.settings"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
